export default {
    ADD_POST: "ADD_POST",
    DELETE_POST: "DELETE_POST",
    UPDATE_POST: "UPDATE_POST",

    SET_NEW_TITLE: "SET_NEW_TITLE",
    SET_NEW_CONTENT: "SET_NEW_CONTENT",
    SET_NEW_ID: "SET_NEW_ID",
    RESET_NEW: "RESET_NEW",
};